# Default zombie skin
skins.1=1
weights.1=1
# Old "arie" Luukstar
skins.2=2
weights.2=10
# David "the jew" Israel
skins.3=3
weights.3=10
# Lucky "Herobrine" Luuk
skins.4=4
weights.4=1
# Cas "The braindead" 
skins.5=5
weights.5=100
# Max "the zombified bear"
skins.6=6
weights.6=1